networks:
  backend:

services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    tty: true
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - backend

  web:
    container_name: rails_app
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    tty: true
    command: bash -c "bash bin/setup_app.sh"
    volumes:
      - .:/home/app/web
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: quadro_vagas_rb_development
    ports:
      - 3000:3000
    env_file:
      - .env.development
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:
