services:
  app:
    build: .
    tty: true
    command: sh -c 'rm -f tmp/pids/server.pid && rails db:prepare && bin/dev'
    ports:
      - 3000:3000
    depends_on:
      - database
    volumes:
      - .:/app
    environment:
      - DB_HOST=database
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
  database:
    image: postgres:17.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata: