default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>


development:
  <<: *default
  database: quadrovagas-development
  queue:
    <<: *default
    database: storage/quadrovagas-development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate


test:
  <<: *default
  database: quadrovagas-test
  queue:
    <<: *default
    database: storage/quadrovagas-test_queue
    migrations_paths: db/queue_migrate

production:
  <<: *default
  database: quadrovagas-production