name: CI with Test Containers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Run Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Linter
        run: |
          docker compose -f "docker-compose.development.yml" build -q
          docker compose -f "docker-compose.development.yml" run --rm --remove-orphans web bundle exec rubocop

  tests:
    name: Run RSpec Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Test
        run: |
          docker compose -f "docker-compose.development.yml" build -q
          touch log/test.log tmp/local_secret.txt
          chmod 0664 log/test.log tmp/local_secret.txt
          docker compose -f "docker-compose.development.yml" run --rm --remove-orphans web bundle exec rspec

