name: Quadro Vagas CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.221.0
        with:
          bundler-cache: true

      - name: Install bundler-audit
        run: gem install bundler-audit

      - name: Security audit dependencies
        run: bundle-audit check --update

      - name: Lint files
        run: bundle exec rubocop

  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_HOST: localhost
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: quadro_vagas_rb_test
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: quadro_vagas_rb_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        options: >-
            --health-cmd "pg_isready -U postgres"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.221.0
        with:
          bundler-cache: true

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Run tests
        run: bin/rake spec