name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Run Rubocop
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.221.0
        with:
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop

  tests:
    name: Run RSpec Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Rails container
        run: |
          docker compose -f "docker-compose.development.yml" build
          docker compose -f "docker-compose.development.yml" up -d
          echo "Aguardando Rails iniciar..."
          sleep 10
          docker compose -f "docker-compose.development.yml" ps

      - name: Run RSpec Tests
        run: docker exec -u appuser rails_app bundle exec rspec
